
apiVersion: v1
kind: Service
metadata:
  name: bleubankapp-service
  labels:
    app: bluebankapp
spec:
  type: NodePort
  ports:
    - port: 9080
  selector:
    app: bluebankapp

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bluebankapp
  name: bluebankapp  
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bluebankapp
    spec:
      containers:
      - image: mycluster.icp:8500/default/bluebankapp:1.0
        name: bluebankapp
        ports:
        - containerPort: 9080
          protocol: TCP
